### ISSUE TITLE
Retrieve Comments Endpoint

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander-api#10]
As a developer, I can create an API endpoint to retrieve comments so that users can view feedback on Wi-Fi spots.

### Task
- [x] Design the read comment endpoint
- [x] Fetch comments from the database
- [x] Add error checks

### Acceptance criteria
- [x] The endpoint returns a list of comments for a specific Wi-Fi spot
- [x] The data is correctly fetched and formatted
- [x] Correct error messages are returned if there is an error
