### ISSUE TITLE
Delete Comment Endpoint

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander-api#11]
As a developer, I can create an API endpoint to delete comments so that users can manage their feedback.

### Task
- [x] Design the delete comment endpoint
- [x] Add in input validation to check for authorised users 
- [x] Remove the comment data from the database
- [x] Ensure only the user who created the comment or an admin can delete it
- [x] Add error checks

### Acceptance criteria
- [x] The endpoint deletes the specified comment
- [x] Only the user who created the comment or an admin can delete it
- [x] Correct error messages are returned if there is an error
