### ISSUE TITLE
Add Rating Endpoint

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander-api#12]
As a developer, I can create an API endpoint to add ratings so that users can rate Wi-Fi spots.

### Task
- [ ] Design the create rating endpoint
- [ ] add input validation
- [ ] Save the rating to the database
- [ ] Ensure only authenticated users can add ratings
- [ ] Add error checks

### Acceptance criteria
- [ ] The endpoint accepts valid rating data and saves it to the database
- [ ] Only authenticated users can add ratings
- [ ] Correct error messages are returned if there is an error
- [ ] User authentication is verified before adding a rating
