### ISSUE TITLE
Password Reset Endpoint

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander-api#4]
As a developer, I can create an API endpoint for password reset so that users can recover access to their accounts.

### Task
- [ ] Design the password reset endpoint
- [ ] add input validation
- [ ] Update the database with the new password once reset
- [ ] Add error checks for invalid email addresses and memorable words

### Acceptance criteria
- [ ] The password reset endpoint accepts valid email addresses
- [ ] Password reset correctly resets the password
- [ ] Correct error messages are returned if there is an error
