### ISSUE TITLE
Retrieve WIFI Location

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander-api#6]
As a developer, I can create an API endpoint to retrieve Wi-Fi locations so that users can view available locations.

### Task
- [x] Design the read Wi-Fi spot endpoint
- [x] Implement pagination and filtering options
- [x] Fetch data from the database
- [x] Add error checks

### Acceptance criteria
- [x] The endpoint returns a list of Wi-Fi spots based on query parameters i.e city, county
- [x] The data is correctly fetched and formatted
- [x] Correct error messages are returned if there is an error
