### ISSUE TITLE
Delete WIFI Location

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander-api#8]
As a developer, I can create an API endpoint to delete Wi-Fi spots so that authenticated users can remove their contributions.

### Task
- [x] Design the delete Wi-Fi spot endpoint
- [x] add input validation
- [x] Remove the Wi-Fi spot data from the database
- [x] Ensure only the user who created the spot or an admin can delete it
- [x] Add error checks

### Acceptance criteria
- [x] The endpoint deletes the specified Wi-Fi spot.
- [x] Only the user who created the spot or an admin can delete it
- [x] Correct error messages are returned if there is an error
