### ISSUE TITLE
Add Comment Endpoint

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander-api#9]
As a developer, I can create an API endpoint to add comments so that users can leave feedback on Wi-Fi spots.

### Task
- [x] Design the create comment endpoint
- [x] add input validation
- [x] Save the comment to the database
- [x] Ensure only authenticated users can add comments
- [x] Add error checks

### Acceptance criteria
- [x] The endpoint accepts valid comment data and saves it to the database.
- [x] Only authenticated users can add comments.
- [x] Correct error messages are returned if there is an error
